version: '3'

services:

  www:
    hostname: www
    build: './src/www'
    restart: always
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  api_tasks_create:
    hostname: 'api_tasks_create'
    build: './src/tasks-create/'
    restart: always
    volumes:
      - './src/tasks-create/:/calendario'
      - './src/commons/:/calendario/commons'
      - './data:/calendario/data'

  api_tasks_list:
    hostname: 'api_tasks_list'
    build: './src/tasks-list/'
    restart: always
    volumes:
      - './src/tasks-list/:/calendario'
      - './src/commons/:/calendario/commons'
      - './data:/calendario/data'

  api_tasks_get:
    hostname: 'api_tasks_get'
    build: './src/tasks-get/'
    restart: always
    volumes:
      - './src/tasks-get/:/calendario'
      - './src/commons/:/calendario/commons'
      - './data:/calendario/data'

  api_tasks_update:
    hostname: 'api_tasks_update'
    build: './src/tasks-update/'
    restart: always
    volumes:
      - './src/tasks-update/:/calendario'
      - './src/commons/:/calendario/commons'
      - './data:/calendario/data'
