version: '3'

services:

  app:
    build: './src/app'
    volumes:
      - './src/app/:/app'
    ports:
      - '80:80'

  www:
    image: 'tmvdl/projects:calendar'
    container_name: 'www'
    hostname: 'www'
    build: './src/www'
    volumes:
      - './src/www/:/app'
    ports:
      - '3000:3000'

  api_tasks_create:
    hostname: 'api_tasks_create'
    build: './src/taskscreate/'
    volumes:
      - './src/taskscreate/:/project'
      - './src/main/:/commons'
      - './data:/data'

  api_tasks_list:
    hostname: 'api_tasks_list'
    build: './src/taskslist/'
    volumes:
      - './src/taskslist/:/project'
      - './src/main/:/commons'
      - './data:/data'

  api_tasks_get:
    hostname: 'api_tasks_get'
    build: './src/tasksget/'
    volumes:
      - './src/tasksget/:/project'
      - './src/main/:/commons'
      - './data:/data'

  api_tasks_update:
    hostname: 'api_tasks_update'
    build: './src/tasksupdate/'
    volumes:
      - './src/tasksupdate/:/project'
      - './src/main/:/commons'
      - './data:/data'
