version: '3'

services:

  app:
    image: 'app'
    build: './src'

  www:
    image: 'tmvdl/projects:calendar'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'
